tube_data = {
    "Aldgate": {"Liverpool Street": 1.0, "Tower Hill": 0.8},
    "Aldgate East": {"Tower Hill": 0.9, "Liverpool Street": 0.7},
    "Angel": {"King's Cross St. Pancras": 0.6, "Old Street": 0.5},
    "Baker Street": {"Marylebone": 0.7, "Regent's Park": 0.5, "Edgware Road (C)": 0.9, "Great Portland Street": 0.4, "Bond Street": 0.6},
    "Bank": {"Liverpool Street": 0.8, "St. Paul's": 0.6, "London Bridge": 1.2, "Moorgate": 0.9, "Waterloo": 1.5},
    "Barbican": {"Farringdon": 0.6, "Moorgate": 0.4},
    "Bayswater": {"Paddington": 0.5},
    "Blackfriars": {"Mansion House": 0.4, "Temple": 0.3},
    "Bond Street": {"Marble Arch": 0.5, "Oxford Circus": 0.3, "Green Park": 0.4, "Baker Street": 0.6},
    "Borough": {"London Bridge": 0.7},
    "Cannon Street": {"Mansion House": 0.4, "Monument": 0.3},
    "Chancery Lane": {"Holborn": 0.3, "St. Paul's": 0.4},
    "Charing Cross": {"Embankment": 0.2, "Piccadilly Circus": 0.3, "Leicester Square": 0.4},
    "Covent Garden": {"Holborn": 0.3, "Leicester Square": 0.2},
    "Edgware Road (B)": {"Marylebone": 0.6, "Paddington": 0.3},
    "Edgware Road (C)": {"Paddington": 0.4, "Baker Street": 0.9},
    "Embankment": {"Waterloo": 0.3, "Temple": 0.2, "Westminster": 0.4, "Charing Cross": 0.2},
    "Euston": {"King's Cross St. Pancras": 0.4, "Warren Street": 0.5},
    "Euston Square": {"Great Portland Street": 0.3, "King's Cross St. Pancras": 0.4},
    "Farringdon": {"King's Cross St. Pancras": 0.6, "Barbican": 0.6},
    "Gloucester Road": {"High Street Kensington": 0.4, "South Kensington": 0.3},
    "Goodge Street": {"Tottenham Court Road": 0.3, "Warren Street": 0.4},
    "Great Portland Street": {"Baker Street": 0.4, "Euston Square": 0.3},
    "Green Park": {"Westminster": 0.4, "Hyde Park Corner": 0.7, "Piccadilly Circus": 0.3, "Oxford Circus": 0.3, "Victoria": 0.6, "Bond Street": 0.4},
    "High Street Kensington": {"Gloucester Road": 0.4},
    "Holborn": {"Tottenham Court Road": 0.4, "Russell Square": 0.4, "Chancery Lane": 0.3, "Covent Garden": 0.3},
    "Hyde Park Corner": {"Knightsbridge": 0.7, "Green Park": 0.7},
    "King's Cross St. Pancras": {"Russell Square": 0.6, "Euston Square": 0.4, "Farringdon": 0.6, "Angel": 0.6, "Euston": 0.4},
    "Knightsbridge": {"South Kensington": 0.6, "Hyde Park Corner": 0.7},
    "Lambeth North": {"Waterloo": 0.3},
    "Lancaster Gate": {"Marble Arch": 0.4, "Queensway": 0.2},
    "Leicester Square": {"Tottenham Court Road": 0.3, "Piccadilly Circus": 0.2, "Charing Cross": 0.4, "Covent Garden": 0.2},
    "Liverpool Street": {"Moorgate": 0.5, "Bank": 0.8, "Aldgate": 1.0, "Aldgate East": 0.7},
    "London Bridge": {"Southwark": 0.4, "Bank": 0.9, "Borough": 0.7},
    "Mansion House": {"Blackfriars": 0.4, "Cannon Street": 0.3},
    "Marble Arch": {"Bond Street": 0.5, "Lancaster Gate": 0.4},
    "Marylebone": {"Baker Street": 0.7, "Edgware Road (B)": 0.6},
    "Monument": {"Tower Hill": 0.4, "Cannon Street": 0.3},
    "Moorgate": {"Old Street": 0.6, "Barbican": 0.4, "Liverpool Street": 0.5, "Bank": 0.8},
    "Old Street": {"Angel": 0.5, "Moorgate": 0.6},
    "Oxford Circus": {"Piccadilly Circus": 0.2, "Regent's Park": 0.6, "Tottenham Court Road": 0.3, "Warren Street": 0.4, "Bond Street": 0.3, "Green Park": 0.3},
    "Paddington": {"Edgware Road (B)": 0.3, "Bayswater": 0.5, "Edgware Road (C)": 0.4},
    "Piccadilly Circus": {"Charing Cross": 0.3, "Oxford Circus": 0.2, "Green Park": 0.2, "Leicester Square": 0.2},
    "Pimlico": {"Victoria": 0.6},
    "Queensway": {"Lancaster Gate": 0.2},
    "Regent's Park": {"Baker Street": 0.5, "Oxford Circus": 0.6},
    "Russell Square": {"Holborn": 0.4, "King's Cross St. Pancras": 0.6},
    "Sloane Square": {"South Kensington": 0.7, "Victoria": 0.8},
    "South Kensington": {"Gloucester Road": 0.3, "Sloane Square": 0.7, "Knightsbridge": 0.6},
    "Southwark": {"Waterloo": 0.2, "London Bridge": 0.4},
    "St. James's Park": {"Victoria": 0.4, "Westminster": 0.4},
    "St. Paul's": {"Bank": 0.6, "Chancery Lane": 0.4},
    "Temple": {"Blackfriars": 0.3, "Embankment": 0.2},
    "Tottenham Court Road": {"Holborn": 0.4, "Oxford Circus": 0.3, "Goodge Street": 0.3, "Leicester Square": 0.3},
    "Tower Hill": {"Aldgate": 0.8, "Monument": 0.4, "Aldgate East": 0.8},
    "Victoria": {"Sloane Square": 0.8, "St. James's Park": 0.4, "Green Park": 0.6, "Pimlico": 0.6},
    "Warren Street": {"Euston": 0.5, "Goodge Street": 0.4, "Oxford Circus": 0.4},
    "Waterloo": {"Westminster": 0.4, "Embankment": 0.3, "Lambeth North": 0.3, "Southwark": 0.2, "Bank": 1.5},
    "Westminster": {"Embankment": 0.4, "St. James's Park": 0.4, "Green Park": 0.4, "Waterloo": 0.4}
}